# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(761, 818)
        MainWindow.setMinimumSize(QtCore.QSize(650, 0))
        MainWindow.setWindowTitle("Генератор отчетов для студентов")
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("/* Основной фон */\n"
"QWidget {\n"
"        background-color: #F5F5F5;\n"
"        font-family: \"Times New Roman\";\n"
"        font-size: 16px;\n"
"        color: black;\n"            
"}\n"
"    \n"
"    /* Кнопки */\n"
"    QPushButton {\n"
"        background-color: #2E86AB;\n"
"        color: white;\n"
"        border: 1px solid #1A3E72;\n"
"        border-radius: 4px;\n"
"        padding: 5px 10px;\n"
"        font-weight: bold;\n"
"    }\n"
"    \n"
"    QPushButton:hover {\n"
"        background-color: #1A6A8F;\n"
"    }\n"
"    \n"
"    QPushButton:pressed {\n"
"        background-color: #0D4B6E;\n"
"    }\n"
"    \n"
"    /* Поля ввода */\n"
"    QLineEdit, QComboBox, QSpinBox {\n"
"        background-color: white;\n"
"        border: 1px solid #CCCCCC;\n"
"        border-radius: 3px;\n"
"        padding: 5px;\n"
"    }\n"
"    \n"
"    QComboBox::drop-down {\n"
"        subcontrol-origin: padding;\n"
"        subcontrol-position: top right;\n"
"        width: 20px;\n"
"    }\n"
"    \n"
"    /* Список сохранённых данных */\n"
"    QListWidget {\n"
"        background-color: white;\n"
"        border: 1px solid #CCCCCC;\n"
"        border-radius: 3px;\n"
"    }\n"
"    \n"
"/* Заголовки */\n"
"QLabel {\n"
"     color: #1A3E72;\n"
"      font-weight: bold;\n"
" }\n"
"\n"
"/* Поле текста */\n"
"QTextEdit {\n"
" background-color: white;\n"
"}\n"
"\n"
"/* Выбранная вкладка */\n"
"QTabBar::tab:selected {\n"
"background-color: #2E86AB;\n"
"color: white;\n"
"}\n"
"\n"
"/* Кнопка вопроса */\n"
"QPushButton#questionButton {\n"
"background-color: #F5F5F5;\n"
"border: 0px;\n"
"}"
"QPushButton#questionButton:hover {\n"
"background-color: gray;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setElideMode(QtCore.Qt.TextElideMode.ElideNone)
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(parent=self.tab)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.workTypeBox = QtWidgets.QComboBox(parent=self.tab)
        self.workTypeBox.setEditable(False)
        self.workTypeBox.setFrame(True)
        self.workTypeBox.setObjectName("workTypeBox")
        self.verticalLayout_2.addWidget(self.workTypeBox)
        self.label_2 = QtWidgets.QLabel(parent=self.tab)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.universtyEdit = QtWidgets.QLineEdit(parent=self.tab)
        self.universtyEdit.setObjectName("universtyEdit")
        self.verticalLayout_2.addWidget(self.universtyEdit)
        self.label_8 = QtWidgets.QLabel(parent=self.tab)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_2.addWidget(self.label_8)
        self.cityBox = QtWidgets.QComboBox(parent=self.tab)
        self.cityBox.setEditable(True)
        self.cityBox.setCurrentText("")
        self.cityBox.setObjectName("cityBox")
        self.verticalLayout_2.addWidget(self.cityBox)
        self.label_3 = QtWidgets.QLabel(parent=self.tab)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.facultyEdit = QtWidgets.QLineEdit(parent=self.tab)
        self.facultyEdit.setObjectName("facultyEdit")
        self.verticalLayout_2.addWidget(self.facultyEdit)
        self.label_5 = QtWidgets.QLabel(parent=self.tab)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.subjectEdit = QtWidgets.QLineEdit(parent=self.tab)
        self.subjectEdit.setObjectName("subjectEdit")
        self.verticalLayout_2.addWidget(self.subjectEdit)
        self.label_6 = QtWidgets.QLabel(parent=self.tab)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.topicEdit = QtWidgets.QLineEdit(parent=self.tab)
        self.topicEdit.setObjectName("topicEdit")
        self.verticalLayout_2.addWidget(self.topicEdit)
        self.label_4 = QtWidgets.QLabel(parent=self.tab)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.workNumberBox = QtWidgets.QSpinBox(parent=self.tab)
        self.workNumberBox.setMinimum(1)
        self.workNumberBox.setMaximum(50)
        self.workNumberBox.setObjectName("workNumberBox")
        self.verticalLayout_2.addWidget(self.workNumberBox)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.nextButton1 = QtWidgets.QPushButton(parent=self.tab)
        self.nextButton1.setObjectName("nextButton1")
        self.horizontalLayout.addWidget(self.nextButton1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_7 = QtWidgets.QLabel(parent=self.tab_2)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.label_7)
        self.groupEdit = QtWidgets.QLineEdit(parent=self.tab_2)
        self.groupEdit.setObjectName("groupEdit")
        self.verticalLayout_3.addWidget(self.groupEdit)
        self.label_9 = QtWidgets.QLabel(parent=self.tab_2)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_3.addWidget(self.label_9)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.minusButton = QtWidgets.QPushButton(parent=self.tab_2)
        self.minusButton.setObjectName("minusButton")
        self.horizontalLayout_6.addWidget(self.minusButton)
        self.studentCountLabel = QtWidgets.QLabel(parent=self.tab_2)
        self.studentCountLabel.setObjectName("studentCountLabel")
        self.horizontalLayout_6.addWidget(self.studentCountLabel)
        self.plusButton = QtWidgets.QPushButton(parent=self.tab_2)
        self.plusButton.setObjectName("plusButton")
        self.horizontalLayout_6.addWidget(self.plusButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.label_10 = QtWidgets.QLabel(parent=self.tab_2)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_3.addWidget(self.label_10)
        self.studentEdit1 = QtWidgets.QLineEdit(parent=self.tab_2)
        self.studentEdit1.setObjectName("studentEdit1")
        self.verticalLayout_3.addWidget(self.studentEdit1)
        self.studentLabel2 = QtWidgets.QLabel(parent=self.tab_2)
        self.studentLabel2.setObjectName("studentLabel2")
        self.verticalLayout_3.addWidget(self.studentLabel2)
        self.studentEdit2 = QtWidgets.QLineEdit(parent=self.tab_2)
        self.studentEdit2.setDragEnabled(False)
        self.studentEdit2.setReadOnly(True)
        self.studentEdit2.setPlaceholderText("")
        self.studentEdit2.setObjectName("studentEdit2")
        self.verticalLayout_3.addWidget(self.studentEdit2)
        self.studentLabel3 = QtWidgets.QLabel(parent=self.tab_2)
        self.studentLabel3.setObjectName("studentLabel3")
        self.verticalLayout_3.addWidget(self.studentLabel3)
        self.studentEdit3 = QtWidgets.QLineEdit(parent=self.tab_2)
        self.studentEdit3.setReadOnly(True)
        self.studentEdit3.setPlaceholderText("")
        self.studentEdit3.setObjectName("studentEdit3")
        self.verticalLayout_3.addWidget(self.studentEdit3)
        self.studentLabel4 = QtWidgets.QLabel(parent=self.tab_2)
        self.studentLabel4.setObjectName("studentLabel4")
        self.verticalLayout_3.addWidget(self.studentLabel4)
        self.studentEdit4 = QtWidgets.QLineEdit(parent=self.tab_2)
        self.studentEdit4.setReadOnly(True)
        self.studentEdit4.setPlaceholderText("")
        self.studentEdit4.setObjectName("studentEdit4")
        self.verticalLayout_3.addWidget(self.studentEdit4)
        self.studentLabel5 = QtWidgets.QLabel(parent=self.tab_2)
        self.studentLabel5.setObjectName("studentLabel5")
        self.verticalLayout_3.addWidget(self.studentLabel5)
        self.studentEdit5 = QtWidgets.QLineEdit(parent=self.tab_2)
        self.studentEdit5.setReadOnly(True)
        self.studentEdit5.setPlaceholderText("")
        self.studentEdit5.setObjectName("studentEdit5")
        self.verticalLayout_3.addWidget(self.studentEdit5)
        self.label_15 = QtWidgets.QLabel(parent=self.tab_2)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_3.addWidget(self.label_15)
        self.teacherEdit = QtWidgets.QLineEdit(parent=self.tab_2)
        self.teacherEdit.setObjectName("teacherEdit")
        self.verticalLayout_3.addWidget(self.teacherEdit)
        self.label_16 = QtWidgets.QLabel(parent=self.tab_2)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_3.addWidget(self.label_16)
        self.postEdit = QtWidgets.QLineEdit(parent=self.tab_2)
        self.postEdit.setObjectName("postEdit")
        self.verticalLayout_3.addWidget(self.postEdit)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.backButton1 = QtWidgets.QPushButton(parent=self.tab_2)
        self.backButton1.setObjectName("backButton1")
        self.horizontalLayout_2.addWidget(self.backButton1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.nextButton2 = QtWidgets.QPushButton(parent=self.tab_2)
        self.nextButton2.setObjectName("nextButton2")
        self.horizontalLayout_2.addWidget(self.nextButton2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_17 = QtWidgets.QLabel(parent=self.tab_3)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_4.addWidget(self.label_17)
        self.purposeText = QtWidgets.QTextEdit(parent=self.tab_3)
        self.purposeText.setPlaceholderText("")
        self.purposeText.setObjectName("purposeText")
        self.verticalLayout_4.addWidget(self.purposeText)
        self.label_18 = QtWidgets.QLabel(parent=self.tab_3)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_4.addWidget(self.label_18)
        self.progressText = QtWidgets.QTextEdit(parent=self.tab_3)
        self.progressText.setPlaceholderText("")
        self.progressText.setObjectName("progressText")
        self.verticalLayout_4.addWidget(self.progressText)
        self.label_19 = QtWidgets.QLabel(parent=self.tab_3)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_4.addWidget(self.label_19)
        self.conclusionText = QtWidgets.QTextEdit(parent=self.tab_3)
        self.conclusionText.setPlaceholderText("")
        self.conclusionText.setObjectName("conclusionText")
        self.verticalLayout_4.addWidget(self.conclusionText)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_4.addItem(spacerItem5)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.backButton2 = QtWidgets.QPushButton(parent=self.tab_3)
        self.backButton2.setObjectName("backButton2")
        self.horizontalLayout_3.addWidget(self.backButton2)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.nextButton3 = QtWidgets.QPushButton(parent=self.tab_3)
        self.nextButton3.setObjectName("nextButton3")
        self.horizontalLayout_3.addWidget(self.nextButton3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_20 = QtWidgets.QLabel(parent=self.tab_4)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_7.addWidget(self.label_20)
        self.questionButton = QtWidgets.QPushButton(parent=self.tab_4)
        self.questionButton.setText("")
        self.questionButton.setObjectName("questionButton")
        self.horizontalLayout_7.addWidget(self.questionButton)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem7)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.templateFileEdit = QtWidgets.QLineEdit(parent=self.tab_4)
        self.templateFileEdit.setReadOnly(True)
        self.templateFileEdit.setObjectName("templateFileEdit")
        self.horizontalLayout_4.addWidget(self.templateFileEdit)
        self.changeButton = QtWidgets.QPushButton(parent=self.tab_4)
        self.changeButton.setObjectName("changeButton")
        self.horizontalLayout_4.addWidget(self.changeButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.label_21 = QtWidgets.QLabel(parent=self.tab_4)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_5.addWidget(self.label_21)
        self.formatBox = QtWidgets.QComboBox(parent=self.tab_4)
        self.formatBox.setObjectName("formatBox")
        self.verticalLayout_5.addWidget(self.formatBox)
        self.label_22 = QtWidgets.QLabel(parent=self.tab_4)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_5.addWidget(self.label_22)
        self.fileNameEdit = QtWidgets.QLineEdit(parent=self.tab_4)
        self.fileNameEdit.setObjectName("fileNameEdit")
        self.verticalLayout_5.addWidget(self.fileNameEdit)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_5.addItem(spacerItem8)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.backButton3 = QtWidgets.QPushButton(parent=self.tab_4)
        self.backButton3.setObjectName("backButton3")
        self.horizontalLayout_5.addWidget(self.backButton3)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem9)
        self.createReportButton = QtWidgets.QPushButton(parent=self.tab_4)
        self.createReportButton.setObjectName("createReportButton")
        self.horizontalLayout_5.addWidget(self.createReportButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.tabWidget.addTab(self.tab_4, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate("MainWindow", "Вид работы"))
        self.label_2.setText(_translate("MainWindow", "Название учебного учреждения"))
        self.universtyEdit.setPlaceholderText(_translate("MainWindow", "Уфимский университет науки и технологий"))
        self.label_8.setText(_translate("MainWindow", "Город"))
        self.label_3.setText(_translate("MainWindow", "Название кафедры"))
        self.facultyEdit.setPlaceholderText(_translate("MainWindow", "ВМиК"))
        self.label_5.setText(_translate("MainWindow", "Название дисциплины"))
        self.subjectEdit.setPlaceholderText(_translate("MainWindow", "Языки программирования"))
        self.label_6.setText(_translate("MainWindow", "Тема работы"))
        self.topicEdit.setPlaceholderText(_translate("MainWindow", "Автоматизация рутинных процессов"))
        self.label_4.setText(_translate("MainWindow", "Номер работы"))
        self.nextButton1.setText(_translate("MainWindow", "Далее"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Титульный лист"))
        self.label_7.setText(_translate("MainWindow", "Группа"))
        self.groupEdit.setPlaceholderText(_translate("MainWindow", "ПРО-202Б"))
        self.label_9.setText(_translate("MainWindow", "Кол-во студентов, выполнявших работу"))
        self.minusButton.setText(_translate("MainWindow", "-"))
        self.studentCountLabel.setText(_translate("MainWindow", "1"))
        self.plusButton.setText(_translate("MainWindow", "+"))
        self.label_10.setText(_translate("MainWindow", "Студент 1"))
        self.studentEdit1.setPlaceholderText(_translate("MainWindow", "Фамилия И.О."))
        self.studentLabel2.setText(_translate("MainWindow", "Студент 2"))
        self.studentLabel3.setText(_translate("MainWindow", "Студент 3"))
        self.studentLabel4.setText(_translate("MainWindow", "Студент 4"))
        self.studentLabel5.setText(_translate("MainWindow", "Студент 5"))
        self.label_15.setText(_translate("MainWindow", "ФИО проверяющего"))
        self.teacherEdit.setPlaceholderText(_translate("MainWindow", "Фамилия И.О."))
        self.label_16.setText(_translate("MainWindow", "Должность проверяющего"))
        self.postEdit.setPlaceholderText(_translate("MainWindow", "Старший преподаватель"))
        self.backButton1.setText(_translate("MainWindow", "Назад"))
        self.nextButton2.setText(_translate("MainWindow", "Далее"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Выполнил/Проверил"))
        self.label_17.setText(_translate("MainWindow", "Цель работы"))
        self.purposeText.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Times New Roman\'; font-size:16px; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">Изучить...</span></p></body></html>"))
        self.label_18.setText(_translate("MainWindow", "Ход работы"))
        self.progressText.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Times New Roman\'; font-size:16px; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">В ходе выполнения данной работы следует...</span></p></body></html>"))
        self.label_19.setText(_translate("MainWindow", "Вывод"))
        self.conclusionText.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Times New Roman\'; font-size:16px; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">В ходе выполнения данной работы было изучено...</span></p></body></html>"))
        self.backButton2.setText(_translate("MainWindow", "Назад"))
        self.nextButton3.setText(_translate("MainWindow", "Далее"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Содержание"))
        self.label_20.setText(_translate("MainWindow", "Файл шаблона"))
        self.changeButton.setText(_translate("MainWindow", "Изменить"))
        self.label_21.setText(_translate("MainWindow", "Формат файла отчета"))
        self.label_22.setText(_translate("MainWindow", "Имя файла отчета"))
        self.fileNameEdit.setPlaceholderText(_translate("MainWindow", "ЛР_Отчет_1_ФИО"))
        self.backButton3.setText(_translate("MainWindow", "Назад"))
        self.createReportButton.setText(_translate("MainWindow", "Создать отчет"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Формат отчета"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
